### ISSUE TITLE
Song Smith MAA art

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#689] opened 2023-02-19 21:10 UTC
![image](https://user-images.githubusercontent.com/76008882/219975144-c0656cd3-7ee0-4d13-bdbe-43c6f891fa13.png)

**Comment by jj248** [comment] 2023-02-20 11:42
Have assigned them as trebuchets for now.

**Comment by Jauffr** [comment] 2023-02-24 00:53
Song Smiths do in fact have the Trebuchet GFX currently as intended 
![Screenshot 2023-02-23 175243](https://user-images.githubusercontent.com/108106660/221065268-c2ed0ac0-2853-4110-bb68-1f36ce403cee.png)

**Comment by Remerod** [comment] 2023-02-24 00:56
So does 

> Have assigned them as trebuchets for now.

mean that this issue is done now because they have them now "or" are we gonna wait to make a proper one for them, maybe with the **Stable diffusion** tool?

**Comment by VectorMaximus** [comment] 2023-02-24 00:58
Preferably assign a proper one, likely generated via stable diffusion. The Trebuchets are placeholders.

**Comment by jj248** [comment] 2023-02-25 22:17
Agreed - pushing this back to the Art column now, given it's no longer bugged.

**Comment by jj248** [comment] 2023-04-24 23:34
Added - ready to test.

**Comment by Remerod** [comment] 2023-04-27 12:40
they do indeed have one now! i think it works ;)

![image](https://user-images.githubusercontent.com/79544635/234864156-1f08bc2d-67d4-4501-82e8-358b64966fec.png)

Although it's funny, since we changed for only the Calaquendi heritage to have it, very few can have it now, and all other noldor MAA (i think) don't have unique MAA :P

Either-way this is now working so i am closing this!, good job :)

**Closed by Remerod** 2023-04-27 12:40 UTC
Labels: oddity, priority: medium, 2D graphics
