### ISSUE TITLE
Dol Amroth forever alone in the Kinstrife

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#729] opened 2023-02-24 07:52 UTC
When the Kinstrife events pop up, even when the vassal princes choose to support Aragorn they end up on the Steward's side. So Dol Amroth never has any allies

**Comment by jj248** [comment] 2023-02-27 21:35
Should be fixed once again.  Ready to test.
![image](https://user-images.githubusercontent.com/26043074/221690933-b84748a4-5c31-4943-971b-81f7325ce2fe.png)

**Comment by Jauffr** [comment] 2023-02-28 01:20
The Kin strife works as intended. Dol Amroth has support in the war on the royalist side
![Screenshot 2023-02-27 181606](https://user-images.githubusercontent.com/108106660/221727871-0300d92d-2914-4185-9409-416f1e556754.png)
![Screenshot 2023-02-27 181803](https://user-images.githubusercontent.com/108106660/221727877-b2dde3f6-2dbf-4b9d-856d-2f7af4db0717.png)

**Closed** 2023-02-28 23:08 UTC
Labels: bug, priority: medium, events
