### ISSUE TITLE
Eowealfa / Leofring - Make the Vale great again decision

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#530] opened 2022-10-06 09:19 UTC
Drive any non-Rohirric type cultures out of the vale of Anduin.

**Comment by JukeJukestar** [comment] 2022-11-24 10:35
This is not very detailed on what it means, Im assuming its a decision?
I would say let regular gameplay mechanics (culture conversion, hybridizing) handle this one

**Comment by jj248** [comment] 2022-11-24 10:37
> This is not very detailed on what it means, Im assuming its a decision? I would say let regular gameplay mechanics (culture conversion, hybridizing) handle this one

It's really just some sort of decision to give a reward or gameplay direction for these people.  Happy to hear suggestions!

**Comment by RedArkady** [comment] 2022-11-24 10:40
Yeah they're set up (e.g. in their starting event) to have a broad rivalry with the encroaching Valemen, so this will be an extension of that. It's on my list!

**Comment by RedArkady** [comment] 2023-01-15 16:41
New 'Restore the Éothéod' Decision implemented.

Need to check whether the decision disappears from the options once its been taken.

**Comment by jj248** [comment] 2023-01-15 20:31
Have also added a Unify the Éothéod, cultural unification decision.

**Comment by Jauffr** [comment] 2023-02-24 01:40
As anyone who participated in, or observed the Eotheod MP will agree. The decisions are working as intended. I will however suggest that the Reunite the Eotheod decision would also include the valemen counties in its % chance to convert people to Eotheod culture. It was awkward at the end of the MP to see all the valemen unaffected by the decision. They may not be Eotheod, however you can easily handwave it by the fact that they live in the heart of the new Eotheod realm. They could either be adopting the traditions of their new lieges, or simply becoming minorities in some counties as they new wave of Eotheod numbers outnumber them. Perhaps only giving them a 50% chance to flip instead of 60 though. Even 40% would would be enough

**Comment by Jauffr** [comment] 2023-02-24 01:44
The only issue we ran into was the fact that vassal characters are not given an event to choose to convert

**Comment by jj248** [comment] 2023-02-25 22:22
Agreed - I need to add a global announcement and an event to players in the area affected by the culture change.

**Comment by jj248** [comment] 2023-02-28 13:33
Will deal with Global Announcement as part of that issue, otherwise, there should now be an event for players affected by the decision to decide if they want to culture convert.

**Comment by savagesach** [comment] 2023-02-28 23:56
The restore the kingdom of the eotheod decision is bugged, taking it does not actually give the modifier that it's supposed to
![image](https://user-images.githubusercontent.com/86676697/222009946-20f1d003-47e5-4ba4-b9dd-75dd2070ad36.png)
![image](https://user-images.githubusercontent.com/86676697/222009966-e0507c6a-8c6d-4137-9eb7-1465909a005a.png)

**Comment by savagesach** [comment] 2023-03-01 00:09
Also the reunite the eotheod decision still requires rhosgobel, which I don't think should be included since that would mean you'd have to fight lorien. Not that you don't have to fight them for parth celebrant anyway but still
![image](https://user-images.githubusercontent.com/86676697/222011585-804e2ccb-dc6a-4fa8-8d62-e1327fe69310.png)

**Comment by savagesach** [comment] 2023-03-01 00:15
so this is what the culture map looked like post decision, I think it needs a massive nerf. Personally I'd be in favor of 40% converting rather than 60%
![image](https://user-images.githubusercontent.com/86676697/222012331-98b59b6f-6050-4c88-85b8-b9618b7b9093.png)

**Comment by jj248** [comment] 2023-03-01 09:32
@savagesach - I take the point on the Kingdom decision, I'll fix that.  Otherwise I generally side with Jauffre's comments on the % of culture converted and the fact that it makes woodmen push into the forest.  I guess I could make it so that the county only has a chance to convert if the province is already a Eotheod heritage culture or has an Eotheod ruler...

**Comment by RedArkady** [comment] 2023-03-01 11:30
I'll fix that Special building loc issue.

**Comment by RedArkady** [comment] 2023-03-01 11:43
I'm probably being thick but I could use more clarity on what is meant by "taking it does not actually give the modifier that it's supposed to".

**Comment by RedArkady** [comment] 2023-03-08 10:04
I found and fixed the broken special building loc issue - apologies for forgetting to update here.

**Comment by JukeJukestar** [comment] 2023-03-11 12:22
The county modifier from restoring the eotheod should be fixed.

**Comment by Jauffr** [comment] 2023-03-11 15:58
I don't have a screenshot on hand for it, but I have most definitely seen it working

**Comment by savagesach** [comment] 2023-03-13 13:39
![image](https://user-images.githubusercontent.com/86676697/224718436-71487035-5e54-424d-8d32-81be77b32cc3.png)
okay I had to unpause first, this is a nice event. I think if this text was added in the bigger event instead, it would be much better

**Closed** 2023-03-18 14:13 UTC
Labels: priority: medium, decisions
