### ISSUE TITLE
If Aragorn dies early after marrying Arwen, she should not die immediately after if her children are still babies

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#948] opened 2023-07-23 15:43 UTC
Arwen should stay in Gondor until her children reach adulthood at least

**Comment by jj248** [comment] 2024-01-04 22:41
Makes sense, I guess! I'll look into it.

**Comment by jj248** [comment] 2024-01-05 09:51
@JukeJukestar - I've updated so that we check if she has any children under 16 and if so, she'll delay her death by a number of years between 10 and 15. Does that work for you?

`if = {
				limit = {
					any_child = {
						age < 16
					}
				}
				trigger_event = {
					id = gondor.0519
					years = {10 15 }
				}
			}
			else = {
				trigger_event = {
					id = gondor.0519
					years = 1
				}
			}`

**Comment by BriceLeduc** [comment] 2024-01-05 10:23
I've added code that check that Arwen is married to Aragorn (and alive) when firing the pregnancy events, and if Aragorn dies while she is pregnant sends the birth event to her instead (she needs to be alive whether he is alive or not). That should take care of any contingency

**Comment by jj248** [comment] 2024-01-05 10:40
Sounds like we're ready to test! @savagesach @Hendrix1337x <3

**Comment by Hendrix1337x** [comment] 2024-01-05 16:03
this seems to be working as intended
![8](https://github.com/jj248/RealmsInExile/assets/154389264/6749c48c-4741-438f-8c47-651ff61c569d)
![9](https://github.com/jj248/RealmsInExile/assets/154389264/2f340e75-8fea-4be7-8a10-efdc4fd7203a)

**Comment by jj248** [comment] 2024-01-06 11:29
Perfect - closing then. Thanks all.

**Closed by jj248** 2024-01-06 11:29 UTC
Labels: Basic Scripting
