### ISSUE TITLE
Vassal tribe orcs of Saruman use Fallen Istari culture COA. 

### ISSUE THREAD

**Issue by zartaxxx** [jj248/RealmsInExile#326] opened 2022-02-26 17:49 UTC
It happens when a tribe vassal dies without heir and the title goes to Saruman. AI Saruman automatically gives it to randomly spawned orc of his culture(Fallen Istari). So when new orc converts to orc culture he stil uses Fallen Istari COA
![image](https://user-images.githubusercontent.com/66900533/155853751-4dfe5b6c-9e90-469b-9a81-39b45fe64c87.png)
![image](https://user-images.githubusercontent.com/66900533/155853761-9dcafdce-bba3-4130-ae13-fd617db598a6.png)

**Comment by Remerod** [comment] 2022-02-27 00:55
It might be a case of them having Continental Eurpoean as their cultural coat of Arm, all other cultures have a custom LOTR one 

![image](https://user-images.githubusercontent.com/79544635/155863833-a1f91ab6-a2af-4e27-8a42-4c2076d0d91d.png)

**Comment by jj248** [comment] 2023-01-18 14:57
These should all now have orc CoAs by looking at the files.  Pushing back to testers to confirm.

**Comment by Jauffr** [comment] 2023-02-28 01:39
Orcs generated this way have the correct COA, however they also can be converted to local cultures instead of orcs
![Screenshot 2023-02-27 183801](https://user-images.githubusercontent.com/108106660/221730509-8d70aba6-9100-49c9-8d3d-0975ac299ce8.png)

**Comment by JukeJukestar** [comment] 2023-03-11 12:18
Huh! Movin this to bugs then?

**Comment by jj248** [comment] 2023-03-20 15:14
Should hopefully be fixed.  It was the racial conversion event converting landed new fallen istari characters to local faith and culture.

**Comment by Remerod** [comment] 2023-03-22 22:26
Could swear i saw rhorric orcs the other day i was playing, just as Jauffre was showcasing the other above in his last message, i'll see if i can find a picture of it

**Comment by Remerod** [comment] 2023-03-22 23:31
ok the culture thing seems to be working in the game i was looking in now

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/227061340-591ac7b5-b3af-4def-88af-d87d204c3582.png)
pre-auto-converting to a new culture

![image](https://user-images.githubusercontent.com/79544635/227061389-f05fea10-23b6-480e-a94a-8ba09391d994.png)
correctly converting

</details>

But the CoA are still mixed by orcs and non orcs
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/227061532-ad110a95-35db-4dc7-bc7f-b39f216a63c5.png)
showing both, it's over all pretty 50-50

</details>

> It happens when a tribe vassal dies without heir and the title goes to Saruman. AI Saruman automatically gives it to randomly spawned orc of his culture(Fallen Istari). So when new orc converts to orc culture he stil uses Fallen Istari COA

so i am unsure this is fixed

**Comment by savagesach** [comment] 2023-04-24 00:42
![image](https://user-images.githubusercontent.com/86676697/233876131-2e4777e2-57fe-40f7-bcf3-209628cd21b2.png)
![image](https://user-images.githubusercontent.com/86676697/233876167-93eec0c5-0d0c-49ae-9d2c-edc8efda2794.png)
I spent a while looking through my last 5 playthroughs and this is the least orc like coas I found. If these are okay, then the issue is fixed

**Comment by jj248** [comment] 2023-04-24 08:25
Oh yeh - those are OK.  Thanks for testing.  Closing.

**Closed by jj248** 2023-04-24 08:25 UTC
Labels: bug, oddity, localization, priority: medium
