### ISSUE TITLE
Invite Elves to Edhellond

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#705] opened 2023-02-20 23:27 UTC
Decision for Gondor to invite Elves (from Rivendell perhaps? Or maybe Haldir) to take residence as a vassal or protectorate of some kind.
Prerequisites:
Aragorn is the High King & has married Arwen
Is Elendili faith
is a Paragon (not sure about this one)
Has Sindarin as Court Language

I'm not sure about this but maybe have it so that they diverge from whatever Elven culture or that they have either a decision to form a new one in Edhellond, or at the very least when a Edhellond Elven player goes to manually diverge culture it has a unique name. (perhaps they hybridize with the LOTRO Avorrim?)
I think some other prerequisites should be here but unsure and leave it for group discussion recommendations.

**Comment by jj248** [comment] 2023-03-08 11:59
Good idea, but we won't get time to look at this before v3 release, so pushing to content for post v3.

**Comment by Jaco-Daan** [comment] 2023-05-28 00:11
If no-one is going to take a look at this, I'm more than willing to take a look at this, seems fairly simple (compared to other issues that is ;) )

**Comment by Jaco-Daan** [comment] 2023-05-28 03:27
Also, kind of an odd question, but when the player gets to take the decision, should he get an event where he could possibly swap over to play as the elf?

**Comment by JukeJukestar** [comment] 2023-05-28 09:11
I don't see why not? I suppose there wont be much to do though.
You could make Edhellond its own 1-county dejure duchy or kingdom after the decision is taken, though Im not sure if that would vonflict with any code (castamiri etc)

**Comment by Jaco-Daan** [comment] 2023-05-28 19:11
> Decision for Gondor to invite Elves (from Rivendell perhaps? Or maybe Haldir) to take residence as a vassal or protectorate of some kind. Prerequisites: Aragorn is the High King & has married Arwen Is Elendili faith is a Paragon (not sure about this one) Has Sindarin as Court Language
> 
> I'm not sure about this but maybe have it so that they diverge from whatever Elven culture or that they have either a decision to form a new one in Edhellond, or at the very least when a Edhellond Elven player goes to manually diverge culture it has a unique name. (perhaps they hybridize with the LOTRO Avorrim?) I think some other prerequisites should be here but unsure and leave it for group discussion recommendations.

I'm not sure on the restriction for whether Aragorn married Arwen, as it kinda gate keeps the player from taking this decision is he doesn't play on lore friendly settings (obv still a chance of Aragorn marrying Arwen with other lore settings, but it still raises the problem of if someone player on weighted or random lore rule the decision will never be avaiable)

**Comment by blackbird5598** [comment] 2023-06-08 08:16
> Also, kind of an odd question, but when the player gets to take the decision, should he get an event where he could possibly swap over to play as the elf?

I was personally thinking either inviting Haldir and giving his lands to one of his brothers, or inviting his unlanded brother, or inviting Elronds son Elrohir. Those were the people that came to my mind at least.

**Comment by Jaco-Daan** [comment] 2023-06-08 16:39
Well @blackbird5598, the decision and all the events/restrictions are alreaady in, so if you want to take a quick look at it and highlight anything you want changed its all on the To&To branch.

Note, the event ids are as follows:

- gondor.2800 (event where you receive elvess in edhellond !!! if you're debugging this make sure your character is friends with one of the elven rulers)
- gondor.2801 (event where King/Steward of Gondor elevates Edhellond into its own kingdom)
- gondor.2802 (event for the player who invited the elves to swap over to them and play as them)
- gondor.2803 (Gondor gets event for elevating Edhellond IF elves accept)

**Comment by Jauffr** [comment] 2023-06-20 21:56
The decisions all work as intended. While I personally am not fond of the extremely high costs for the kingdom decision and their being a level of fame requirement for Andrast to invite the elves, it is still possible. You already know this though Jaco hehe. I watched you test it and we talked about that ;)
![Screenshot 2023-06-20 151123](https://github.com/jj248/RealmsInExile/assets/108106660/51000591-8a44-41c6-9dfc-14d88132bb2d)
![Screenshot 2023-06-20 153530](https://github.com/jj248/RealmsInExile/assets/108106660/0e4188c2-f0a7-4246-ac12-d63215d90eb0)
![Screenshot 2023-06-20 153219](https://github.com/jj248/RealmsInExile/assets/108106660/aecfcfb1-2e70-4bbd-b65b-47f1fe62dca4)

**Comment by Jauffr** [comment] 2023-06-20 21:58
I do find it funny that the decision is only dissabled for 25 years though. It makes me wonder if the decision to elevate the kingdom of Edhelond would be available again after those 25 years. Not that it would do anything

**Comment by savagesach** [comment] 2023-07-09 03:57
![image](https://github.com/jj248/RealmsInExile/assets/86676697/7dd6b6fb-e801-47a0-b448-f0219af2fe5b)
The invite elves to edhellond decision does not work if you befriend Elrond

**Comment by savagesach** [comment] 2023-07-09 04:01
![image](https://github.com/jj248/RealmsInExile/assets/86676697/31de1d63-89d0-43b3-b016-8d88d5380b5d)
yeah after befriending thranduil, lanthir, galadriel, and elrond, only the first three are options for settling. There should be an option to invite a noldor elf if elrond is befriended

**Comment by Jaco-Daan** [comment] 2023-07-09 05:16
currently its not intended for noldor to be able to settle, as their content isn't fully fleshed out. but it does raise the important fact that Aragorn can befriend Elrond in our current game start.

**Comment by Jaco-Daan** [comment] 2023-07-11 12:55
So the previous bug has been fixed, and all the other playthroughs came out fine, closing

**Closed by Jaco-Daan** 2023-07-11 12:55 UTC
Labels: good first issue, priority: low, decisions
