### ISSUE TITLE
Elven courtship not firing

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#860] opened 2023-04-30 00:44 UTC
When testing the MP with a few of the testers, I couldn't romance a character when playing as one of the elves

**Comment by BriceLeduc** [comment] 2023-05-08 17:36
Pushed a fix, ready for testing

**Comment by savagesach** [comment] 2023-05-08 21:45
![image](https://user-images.githubusercontent.com/86676697/236942294-f0107df7-0074-45dd-9f3d-79ba493946e3.png)
![image](https://user-images.githubusercontent.com/86676697/236942633-e5368795-5f7a-45ef-a7ed-9e01d95cf3e1.png)
as thranduil I arranged a courtship with legolas, then let the game run a few months before switching to legolas. I also tried arranging a courtship myself by playing Ilmarien. In both cases, courtship worked as intended.

**Comment by Remerod** [comment] 2023-05-08 21:46
ok, then i'll close this

**Closed by Remerod** 2023-05-08 21:46 UTC
Labels: bug, priority: critical, scripting
