### ISSUE TITLE
March of the Ents should convert Isengard

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#772] opened 2023-03-14 19:15 UTC
March of the Ents should culture / faith convert Isengard if its Uruk-Hai culture.
The orcs were driven out after all!

**Comment by jj248** [comment] 2023-03-16 08:37
Should be fixed.  Any Rohan victory in the event chain will now convert Isengard to the victor's faith and culture.  Ready to test.

**Comment by savagesach** [comment] 2023-03-22 04:58
This works as intended
![image](https://user-images.githubusercontent.com/86676697/226806140-796d1f5b-a070-4899-855a-e643f2308448.png)

**Closed** 2023-03-22 18:00 UTC
Labels: bug, priority: high
