### ISSUE TITLE
Suggestions Wilderness

### ISSUE THREAD

**Issue by Jermanlordy** [jj248/RealmsInExile#396] opened 2022-04-09 22:39 UTC
Suggestions related to the Wilderness feature:
- [X] Perhaps making wilderness counties very transparant so it looks like terrain instead of a county colour

**Comment by Remerod** [comment] 2022-04-09 23:00
Maybe we should change the localization for the feudal holder over the wilderness/Settlement holding to something? Maybe something like a [Patroon](https://en.wikipedia.org/wiki/Patroon) or something similar? because as of now they become lords, which feel to high of a title for them, (check picture below). 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162594315-2de16caf-4678-4f27-ba53-0e12d56dd3ae.png)
Normal Feudal Count

![image](https://user-images.githubusercontent.com/79544635/162594326-ea8f08d9-b61e-479e-8349-d71a772062d2.png)
Lord over Wilderness of Odharn, feel a bit... as an "overstatement" 

</details>

**Comment by JukeJukestar** [comment] 2022-04-10 12:42
Notes regarding the "Colonized a land recently" modifier

The colonization systems should be handled in a way that allows for later modification and tweaking as development continues.
What I mean by this is that the system should be set up in a way where modifiers such as a cultural tradition or a character buff can impact the time/ cost of a colony.
(Example would be Aragorn getting a 50% colonization speed boost post war of the ring)
Perhaps this could even be made area specific, but I am unsure of ck3s limitations on this stuff.

**Comment by Remerod** [comment] 2022-04-10 12:45
Yeah, optimally i personally think colonization should take between 20-100 years, which different bonuses and maluses affecting the outcome. And maybe in certain cases you should be able to colonize more then one county, like when Aragorn is gonna recolonize Arnor, but that's more an exception to the rule, which should come later if we do it that way.

**Comment by josejuanmartinez** [comment] 2022-04-10 14:48
We need events for the period when the colonization is happening. Ideas:
- Wolves attack (from jamie)
- Spider attacks (Mirkwood)
- Ghost attacks (for lands with ruins, like Eregion)
- Dragon attack (Lonely Mountain, North of Mirkwood - Withered heath, ... ) 
- Wildernes are wastelands (after colonizing - having a random change to get a modifier to the province yields)
- Fertile lands (the opposite)
- Neighbours being pissed considering you an expansionist? (debuff to opinion)
- Neighbours asking you that land for historical reasons
- Finding an old artifact or a treasure
- Shaman encounter
- ...

**Comment by VectorMaximus** [comment] 2022-04-13 00:45
So, currently all wilderness provinces are black. This is great for making them stand out... with the unfortunate result of them standing out, even after they are recolonized. If they could revert to their original color after being colonized, that would be great. If that's not doable, I would personally say to remove the black color. Otherwise they'll be eyesores even after they are colonized.

![image](https://user-images.githubusercontent.com/79318177/163077026-ad19b877-6ae1-4672-b84e-1eadf9b04122.png)

**Comment by JukeJukestar** [comment] 2022-04-15 10:43
Not a bug per se, but the five governments descriptions should be updated to include the new colony holding or link to a textbox explaining colonization mechanics.

**Comment by josejuanmartinez** [comment] 2022-04-19 17:42
@VectorMaximus @RedArkady provinces were restored to their original colour

![image](https://user-images.githubusercontent.com/36634572/164063710-a8d8091e-2868-45ad-b769-9d085e90a65c.png)

**Comment by JukeJukestar** [comment] 2022-04-30 11:49
<details>
<summary>Our Wasteland holdings (look like tribes)</summary>
![image](https://user-images.githubusercontent.com/76008882/166104171-c7e2859b-726b-458c-a05b-b7d80e4c9268.png)

</details>

<details>
<summary>Godherja wasteland holdings (visually empty)</summary>

![image](https://user-images.githubusercontent.com/76008882/166104257-bb2f2c63-62f2-417e-b1df-19ff47334a7a.png)

</details>

would be neat if wasteland holding graphics were changed to be invisible, so it doesnt look like there are tribes there.

**Comment by josejuanmartinez** [comment] 2022-04-30 12:58
@JukeJukestar yep I'm hiding the settlements right now, will be in a while.

**Comment by josejuanmartinez** [comment] 2022-04-30 13:52
@JukeJukestar  Done!

**Comment by RoughlyTheSizeOfAMOROOON** [comment] 2022-10-03 19:11
Moving this idea from a suggestion as per the request of Remerod;

Essentially, add in some Trolls in the mountainous, cold areas to the north of Mirkwood maybe? I figure that they could be a large obstacle to a colonization process, beyond just filling the area with Dragons and the like.

Following this kind of idea, maybe it'd be good to have northern wastelands be harder to colonize? Both because of the frigid weather, and also due to the inhabitants (Trolls, Bears, Wolves, oh my).

**Comment by JukeJukestar** [comment] 2022-10-08 16:26
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/76008882/194717518-20254f85-5768-4023-bd34-01352103acb1.png">

These three counties should be colonized by mordor at game start, so sauron can march his armies through the black gate without suffering lots of attrition.

Lorewise we know that during the war of the ring, bands of orcs patrolled in this area so its not very far-fetched for them to set up some barracks and forts.

**Comment by JukeJukestar** [comment] 2023-03-15 17:42
Closing this issue for now - I dont think we need a unified suggestions issue for wilderness this late in development. If you have an idea, make a discord thread or a new issue

**Closed by JukeJukestar** 2023-03-15 17:42 UTC
Labels: game review, Wilderness
