### ISSUE TITLE
Numenorean Blood: Fertility, Lifespan, Marriage and Dunedain Widowhood

### ISSUE THREAD

**Issue by Rewinged** [jj248/RealmsInExile#164] opened 2021-07-26 10:24 UTC
Look into options for controlling fertility age per race.
Apparently Lord of the Kings have done such a thing through traits, so we can look into how they did it.

**Comment by jj248** [comment] 2021-10-25 00:02
Ready to test.

**Comment by jj248** [comment] 2021-12-17 18:48
Summary of testing seems to be that the above is working with two quirks:

- As it's impossible to betroth someone > 16, it becomes very frustrating for the player to 'time' coming of age for marriages.
- Possibly the AI is still finding a way to marry early, maybe through auto-generation.

Moving back to TO DO pile for fixes.

**Comment by RedArkady** [comment] 2021-12-20 14:42
I don't think the AI is finding a way to marry early, but it is marrying within a day or two of the eligible birthday. And the AI seems to make odd choices - almost always marrying Aragorn's children to low-borns with poor traits - landless, no Númenórean blood, drunkards, etc.

**Comment by jj248** [comment] 2022-01-10 22:11
Pushing back max betrothal age selectively was confirmed by Tobbzn as being not possible.  I suspected as much and, even though Tobbzn isn't the absolute authority on everything, he is the closest thing we have!

Re-enabled the betrothal window at least for Numenorean blood characters.  Ready to retest.

**Comment by JukeJukestar** [comment] 2022-01-15 12:38
Untested, but take a look at how and if the elope scheme is currently handled. the ai tends not to use it much, but it could be possible to elope dunedain characters below their intended marriage age.

The question is should this be changed or not? An elopement isnt really a "legal marriage" as the eloped can have a spouse already, which is replaced in this case.

**Comment by jj248** [comment] 2022-01-15 13:25
Currently I have the same penalty for ages in the elopement acceptance modifiers.  I didn't want the AI to keep breaking the marriage limitations via elopement schemes.

If we really wanted, I could make the penalty only apply to the AI, so that the player can still seek to elope before they are of full age, though that might be an unfair advantage.

**Comment by RedArkady** [comment] 2022-02-03 12:41
I think we need to do something about Númenórean marriage ages, even if it's just tackling the 'can marry' pop-up when it's not yet eligible, but ideally finding some additional way of communicating the non-vanilla changes to the player. It's causing a ton of comments and a fair bit of frustration.

**Comment by Remerod** [comment] 2022-02-03 22:07
I think most players are fine once they know the mechanics, but are as you say frustrated before knowing it. I personally want the mechanic to stay as it is but hopefully add something that showcase it more easily. But that is easier said or asked for in this case then done.

**Comment by jj248** [comment] 2022-02-26 13:18
To avoid confusion I've blocked the 'you can marry betrothed' notification at the top of the screen your betrothed has numenorean blood and would still refuse due to being under their minimum marital age. 

From feedback, I've also reduced down the age limit for tier 3 from 50 to 40.

Think that rounds off the outstanding actions for now - ready to test.

**Comment by Remerod** [comment] 2022-02-26 23:36
the age is now set to 40 and the betrothals can now marry is also set at 40, so it's all good and i'll go ahead and close this! 

![image](https://user-images.githubusercontent.com/79544635/155862312-0a8edfb3-9e92-40ad-b852-ea7483dc032a.png)

**Comment by Jermanlordy** [comment] 2022-03-21 11:25
On the master branch of Dev version all Numenorean Blood tiers dont get the bethrothed can get married notification when they cant,however on the steam version they still get it even when they cant.

**Comment by JukeJukestar** [comment] 2023-01-20 10:26
Theres a big problem with betrothals right now.

As a player, you can seek a betrothal for your child at any age (even with strong blood etc), however, the AI only wants to do it between age 0 and 15. So lets say you have a strong blooded son aged 45, and want to betrothe him to a strong blooded woman aged 26: the AI will not accept this. (marriage age 30)

This leads to a situation where you have to either arrange a betrothal while they are both under 16, or wait for the few month time window once the desired spouse turns 30 (or whatever her marriage age is).

**Comment by jj248** [comment] 2023-03-16 08:33
It's a limitation of the game at the moment unfortunately.  We cannot set different adult ages for characters as these are set out in defines.  I've raised it with Paradox though.

Closing.

**Closed by jj248** 2023-03-16 08:33 UTC
Labels: bug, priority: medium, balance
