### ISSUE TITLE
Galadriel 'the Usurper' takes Tirion

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#754] opened 2023-03-01 03:09 UTC
Galadriel is claiming and usurping Tirion off of her Father Finarfin
![Screenshot 2023-02-28 200747](https://user-images.githubusercontent.com/108106660/222035164-3ce33270-d708-4acf-87bf-bde818ffbd1b.png)

**Comment by savagesach** [comment] 2023-03-01 03:22
it's not just a galadriel issue, I've seen olwe get usurped too. I'm not sure how it's happening though

**Comment by jj248** [comment] 2023-03-08 09:58
I believe this is caused by court event 4200 - "Sanctuary" as it's the only place in vanilla events where the nickname is given out.

The event basically makes an AI primary heir of an AI ally usurp their titles and they flee to you seeking sanctuary.

I've excluded elves from this so hopefully it shouldn't be an issue any more - pushing to testing.

**Comment by Jauffr** [comment] 2023-03-22 22:08
I have not seen here do this in weeks now, so I think it is fair to close it

**Comment by Remerod** [comment] 2023-03-22 22:12
Going on an killing spree with console commands will make is so Galadriel will inherit lands in Valinor

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/227049779-697c528c-0c09-45fc-b29b-d19a56eb97bc.png)

![image](https://user-images.githubusercontent.com/79544635/227049840-30213abc-b52d-4ca8-8254-7c9d7b8cabfe.png)

</details>

So it will still be an issue if there otherstuff outside of "event 4200"

> I have not seen here do this in weeks now, so I think it is fair to close it

but i agree with Jauffre, i haven't seen this around. And if you think that's enough for this issue @jj248 then i think we can close it

**Closed** 2023-03-22 22:11 UTC
Labels: bug, priority: high
