### ISSUE TITLE
Make the High Vracarath more likely to accept vassalization to Variag Kings

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#802] opened 2023-03-22 18:25 UTC
She is pretty reluctant to become anyones vassal because they arent considered her dejure lieges.

It should be done in a way where the King of Upper Khand cant just do it if he holds no lands in lower khand, but she should accept the authority of a king of lower khand or a strong king of upper khand

**Comment by savagesach** [comment] 2023-03-22 18:28
I'd suggest giving the king of lower khand and the king of upper khand separate decisions to vassalize the high vracarath. this way you can make upper khand have harder requirements. as for the requirements, they could be something like be devoted servant, have 5000 troops, and cost 100 gold and 300 prestige

**Comment by jj248** [comment] 2023-04-21 12:55
Vector reports this as done.  Moving to testing.

**Comment by savagesach** [comment] 2023-04-21 20:23
![image](https://user-images.githubusercontent.com/86676697/233726826-3301bed5-2165-4d48-8160-19d72520bb18.png)
![image](https://user-images.githubusercontent.com/86676697/233727049-ec3946b6-ce33-4f7e-b2fe-750f9ec6a910.png)
![image](https://user-images.githubusercontent.com/86676697/233727930-854cb21b-a354-4c7a-897d-618063afd61b.png)
The vassalization buffs work as intended

**Comment by jj248** [comment] 2023-04-21 20:50
Thanks - closing.

**Closed by jj248** 2023-04-21 20:50 UTC
Labels: priority: low, balance
