### ISSUE TITLE
Legacy of the White Hand

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#829] opened 2023-04-15 08:19 UTC
Have a religious deconversion similar to the fall of sauron if saruman dies.
Lidless eye/white hand dunlendings are deconverted to their own "White-Hand Mysticism" gwathuirim faith, rohirrim are freed and orcs become lidless eye.
If I cant get this done before release, we can just comment it out

- [x] Implement White-Hand Mysticism faith
- [x] Disallow conversion until its formed
- [x] Implement religious conversion event
- [x] Find out where and how to trigger the event (on death of saruman? somewhere along the event chain? have to talk about this with @jj248 )
- [ ] Give affected players an extra event that explains what is happening (optional)

**Comment by JukeJukestar** [comment] 2023-04-25 18:51
Moving to testing.
The conversion should trigger:

- if saruman dies
- if saruman is deposed after the rohan invasion war

**Comment by savagesach** [comment] 2023-04-27 20:10
![image](https://user-images.githubusercontent.com/86676697/234979400-6b5a0d9d-23ca-430a-990b-2bba6fb73c3d.png)
this works as intended. I forgot to get an earlier screenshot because I accidentally let the game run while I was eating food

**Comment by Remerod** [comment] 2023-04-27 20:22
one optional thing remaining, but Juke told me to close this, so that is what i'll do

**Closed by Remerod** 2023-04-27 20:22 UTC
Labels: help wanted, priority: medium, scripting
