### ISSUE TITLE
Wilderness Related bugs

### ISSUE THREAD

**Issue by Jermanlordy** [jj248/RealmsInExile#395] opened 2022-04-09 22:38 UTC
Some Bugs related to the Wilderness feature:
- [x] Castle is also named colony
- [x] Colony to Castle takes no time at all

**Comment by Remerod** [comment] 2022-04-09 23:18
Chieftain Pôn have imprisoned the land! this seems like it's not intended.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162594624-d67b2b60-3c6a-44de-ac88-8f5f9933cdd1.png)

![image](https://user-images.githubusercontent.com/79544635/162594653-05196f35-8c9e-40f6-8d1b-dbd482a0ae86.png)
The wilderness might probably have become imprisoned because of them being raided by Chieftain Pôn

</details>

**Comment by JukeJukestar** [comment] 2022-04-09 23:50
- wilderness is assigned character traits and stress traits
- wilderness barony holding has no icon (meaning we get the iconic missing texture pattern when we select the county)
- "trial by combat", "Demand Payment (for hook)", "challenge rival to combat", "buy claim", "propose alliance"
- wilderness cultural tradition is available to anyone diverging or reforming their culture
- hybridizing with wilderness is possible if a county with its culture is somehow obtained (better disable this as a precautionary measure)
- "colonize" character decision is visible on every ruler, would be better and more logical to hide it

there may be more rare character decisions akin to buy claim or trial by combat that are bound to certain skills, faiths or cultures.

**Comment by Remerod** [comment] 2022-04-09 23:59
I'm uncertain when but at one point the wilderness switched to already existing cultures during the observer game i've been running. I don't think this is intended. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162595479-1d978812-3a59-40e7-bfec-147ac5d53924.png)

![image](https://user-images.githubusercontent.com/79544635/162595467-e48aecd4-3218-4904-84f7-c16898edbfa0.png)

![image](https://user-images.githubusercontent.com/79544635/162595494-403b5312-b1af-475b-a192-18228f016796.png)

</details>

**Comment by josejuanmartinez** [comment] 2022-04-10 10:25
Hi @Remerod ! Yes, after you colonize, the holder is a real person, the colonizer.

**Comment by Remerod** [comment] 2022-04-10 11:13
Hi @josejuanmartinez yeah i get that, every pictures from my last comment are the current & former wilderness characters and not any characters who colonized the wilderness

**Comment by josejuanmartinez** [comment] 2022-04-10 14:17
Hi @JukeJukestar !

> ... as a tribal ruler, finishing a colony turns it into a castle, not a tribe
In the document @jj248 had we defined that always, a settlement turns into a castle. So we will discuss if this is expected or needs to be changed.

**Comment by josejuanmartinez** [comment] 2022-04-10 14:17
- [ ] Prevent raids from happen
- [ ] Prevent guests from appearing that will prevent also heirs

**Comment by JukeJukestar** [comment] 2022-04-15 10:40
<details>
<summary>Camp Levy bug</summary>

![image](https://user-images.githubusercontent.com/76008882/163561368-3e424d26-b4d4-4715-a8b1-b7b68e4deeac.png)

</details>

- [ ] Camp -50% levy debuff applies twice because its both a county and a barony effect.
- [ ] Colony -25% levy debuff applies twice because its both a county and a barony effect.

**Comment by josejuanmartinez** [comment] 2022-04-16 17:10
@JukeJukestar  thank you! Duplicated debuffs removed, Paganism faith made impossible to be switched.

**Comment by Remerod** [comment] 2022-04-17 21:36
checking how wilderness fare in observer, after 50 years Swan fell have 3 children (between 30-20 years old) and one guest in their court.  playing the [Restores impossibility of chosing Wastelands as starting nation] update
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/163732780-5ae0cb5d-9492-42f1-a872-ffa41f4eccd7.png)
Wilderness having 3 children, no mother.

![image](https://user-images.githubusercontent.com/79544635/163732797-52f3fa1b-792d-4ad3-9250-a10f168468a6.png)
guest of wilderness of swan fell

</details>

**Comment by josejuanmartinez** [comment] 2022-04-17 21:56
Thanks @Remerod  for pointing you got the last update `Restores impossibility of chosing Wastelands as starting nation`, as I introduced a new bug and was expecting issues until I fixed it :)

I will check this this week.

**Comment by RedArkady** [comment] 2022-04-29 18:33
![Crusader Kings III Screenshot 2022 04 29 - 18 22 37 65](https://user-images.githubusercontent.com/20355423/166004390-d06726ab-e78d-42f2-8698-9fed9d28a32b.png)

Some wars against wilderness appear to be possible.

Also peasant revolts.

**Comment by JukeJukestar** [comment] 2022-04-30 11:39
<details>
<summary>release your stress.. by punching this tree!</summary>

![image](https://user-images.githubusercontent.com/76008882/166103966-1a8f514c-c330-45bf-aaaf-28dc8b5539be.png)

</details>

- [ ] Irritable characters can access the "release your stress" interaction on wilderness

**Comment by josejuanmartinez** [comment] 2022-05-07 18:33
@JukeJukestar  I have tackled all of them. I don't think we want to give the Wilderness government a color though, we may need to discuss this. We have decided to give a transparent colour everywhere - culture, faiths, etc.

I have set "Unsettled" instead of "" for the map.

**Comment by Amducious3D** [comment] 2022-05-26 22:01
https://gyazo.com/e19e8004af8ea78f111f7ca87ba2ce0d
https://gyazo.com/da3535f90c0809c6bbd6462112145b01

**Comment by Amducious3D** [comment] 2022-05-26 22:08
[Wilderness Issue (Was Playing Isengard).zip](https://github.com/MattTheLegoman/RealmsInExile/files/8782401/Wilderness.Issue.Was.Playing.Isengard.zip)

**Comment by josejuanmartinez** [comment] 2022-06-04 12:09
What @Amducious3D  is mentioning seems to be caused by Assemble the Warbands event (thanks @JukeJukestar !).

- [X] UPDATE: I have patched it.

**Comment by JukeJukestar** [comment] 2022-08-21 18:36
![image](https://user-images.githubusercontent.com/76008882/185805824-d5d43466-bc75-46b2-a53d-acc50496b8b2.png)

Theres a typo here, it should be "This is a no man's land."
noman-land is written wrong and saying "these lands are x lands" isnt gramatically wrong but sounds weird

**Comment by JukeJukestar** [comment] 2022-10-09 21:03
@josejuanmartinez I found two more possible wilderness interactions:

- Buy truce, new from fates of iberia
- elvish courting character decision

**Comment by JukeJukestar** [comment] 2022-10-26 18:11
The random "grant neighbor county claim" event from having a bad chancellor can target wilderness

**Comment by JukeJukestar** [comment] 2022-10-26 19:01
![image](https://user-images.githubusercontent.com/76008882/198113479-330470c4-3e1f-49cc-892e-6402dd01305a.png)

another chancellor related wilderness event

**Comment by JukeJukestar** [comment] 2022-10-26 19:19
Another bug: Despotic governments (and Im assuming orkish, elven and other new ones too) cant hold wilderness holdings

**Comment by JukeJukestar** [comment] 2023-02-02 15:40
![image](https://user-images.githubusercontent.com/76008882/216370304-a37ddb6d-6aa2-4a96-b687-5a1ac049f04f.png)

- The gold cost should be displayed above or near the "Colonize" button
- There should be a tooltip saying "not enough gold" when you hover over it and cant colonize - currently it always displays "5 year cooldown" as the reason

**Comment by JukeJukestar** [comment] 2023-02-15 21:54
![image](https://user-images.githubusercontent.com/76008882/219177681-d0fc93f2-b20e-4a5f-8401-b1cabd036480.png)

@jj248 found another one - wilderness can take this interaction

**Comment by JukeJukestar** [comment] 2023-03-15 17:42
We have settled on creating individual new issues for Wilderness bugs, this one hasnt been in use for a long time.
Closing

**Closed by JukeJukestar** 2023-03-15 17:42 UTC
Labels: bug, priority: medium, game review, Wilderness
