### ISSUE TITLE
Elves Drunkard event trait

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#699] opened 2023-02-20 01:19 UTC
![image](https://user-images.githubusercontent.com/125709421/219988323-e8a636ef-a595-44ba-867f-e1407c19df70.png)

just a event that gives you the change of becoming a drunkard as a elf second time its happened.

**Comment by Remerod** [comment] 2023-02-20 01:30
again as i mentioned in an other issue, you leave to much to the imagination, you explain that an event have happened to you. You should explain the event happening to you as of whom you play as and around when, probably the cause of it and **why** it is a problem, the very bug or problem of the report always need to be clear and not left to guesswork

**Comment by jj248** [comment] 2023-02-20 10:38
Blocked for elves and AI lore characters.  Ready to test.

**Comment by Jauffr** [comment] 2023-03-23 05:16
Something is still able to give elves the drunkard trait. I don't know what it is though
![Screenshot 2023-03-22 231523](https://user-images.githubusercontent.com/108106660/227109949-61972175-cd1b-4b61-ba71-3e0f7b0a5b3d.png)

**Comment by BriceLeduc** [comment] 2023-04-03 10:14
I've pushed a fix : Elves should no longer become drunkards

**Comment by savagesach** [comment] 2023-04-27 20:13
![image](https://user-images.githubusercontent.com/86676697/234980264-34bb718f-b3cc-45fe-afa3-3cc87ee8a395.png)
galadriel can still become a drunkard

**Comment by Remerod** [comment] 2023-04-27 20:15
moving this to bugs again then

**Comment by BriceLeduc** [comment] 2023-04-28 11:47
pushed a fix, moving to testing

**Closed** 2023-07-06 16:54 UTC
Labels: bug, oddity, priority: low, events
