### ISSUE TITLE
Orthanc palantir texture bug  

### ISSUE THREAD

**Issue by Chief305** [jj248/RealmsInExile#354] opened 2022-03-23 12:16 UTC
when in the court the orthanc palantir turns grey in certain camera angles 

<details>
<summary>Click to expand</summary>

![20220323080425_1](https://user-images.githubusercontent.com/99970173/159697026-15c05ced-3c08-4f70-8afc-8ee621753b43.jpg)

</details>

**Comment by Chief305** [comment] 2022-03-23 12:17
ver 2.3 compatch

**Comment by jj248** [comment] 2023-01-18 10:39
I've messed around with the textures, but it's not perfect by any stretch.  The issue is with the normal texture. 
![image](https://user-images.githubusercontent.com/26043074/213150466-18997b05-9dbe-49c9-b5d8-6c3ff6eadf51.png)

**Comment by jj248** [comment] 2023-01-18 10:44
@MattTheLegoman - I know you've taken a look at this before, but I'll leave this with you to look at.  I think we either accept it as it is and close the issue, or you see if you can resolve the normal issue.  I'm at the limit of what I can do on this with my artistic abilities.

**Comment by jj248** [comment] 2023-04-21 12:58
I've done what I can on this - one for Matt or a future 3D artist to look into.  Moving to v4.

**Comment by Rewinged** [comment] 2023-05-26 11:55
Fixed in RoCo compatch branch

**Closed by Rewinged** 2023-05-26 11:55 UTC
Labels: bug, oddity, priority: high, 3D graphics
