### ISSUE TITLE
Balancing activity costs

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#923] opened 2023-06-09 14:09 UTC
As our cultures start mostly in the last age, the activity costs are absolutely massive : over 600g for a feast for Denethor.
This needs to be toned down if we want people to be able to use them before 2-3 centuries

**Comment by JukeJukestar** [comment] 2023-06-22 13:21
Agreed, problem is that we start at the very end of the tech tree but with development roughly equal to 1066

**Comment by Jaco-Daan** [comment] 2023-06-22 13:26
Jamie adjusted the costs for this, moving to testing

**Comment by savagesach** [comment] 2023-07-09 03:36
I've been testing for the past two weeks and I think the activity costs are balanced now. This works as intended.

**Closed** 2023-07-09 07:24 UTC
Labels: priority: critical, balance, scripting, Ready for Testing
