### ISSUE TITLE
Izindubêth Head of Faith shatters on succession/ generates female heirs

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#776] opened 2023-03-15 15:16 UTC
![image](https://user-images.githubusercontent.com/76008882/225355017-7245234a-b535-43da-a994-a8d0b8e23fa0.png)

![image](https://user-images.githubusercontent.com/76008882/225355454-e70cf7d4-ce15-4bb9-a861-afda8eaff321.png)
Here we see it generating three women in a row before generating one man

It used to be male only, I believe we changed it to male preference because the game would destroy the title when a woman inherited.
For some reason, women inherit a lot of the time.
Theocratic succession law may be broken somehow.

A possible solution would be to just set the Batân an-Izindi faith to have male only clergy

**Comment by jj248** [comment] 2023-03-16 08:32
Shoud be fixed, ready to test

**Comment by JukeJukestar** [comment] 2023-03-22 18:09
![image](https://user-images.githubusercontent.com/76008882/226998354-db6c1344-e8a7-4e22-acad-c894f533e18d.png)

We now have the same issue as in 2.3
A woman still inherits, but the title is destroyed because its male only.

**Comment by Remerod** [comment] 2023-03-22 19:26
I don't understand, did you confirm that what jamie wrote:

> 
Shoud be fixed, ready to test

was not working or did you just point out that it also dosen't work on 2.3 @JukeJukestar ?

**Comment by JukeJukestar** [comment] 2023-04-01 09:19
I was trying to say that its still broken after the fix.
Back in 2.3, the head of faith was male only and often times a woman would inherit anyways, causing the title to be destroyed.
We at some point changed it during 3.0 development so its male preference, which lead to lots of female Izindubêths.
Jamie didnt specify what his fix was, but apparently he just set inheritance back to male only, which causes the head of faith title to be destroyed.

By the way, lorewise vec says women can theoretically become Inzidûbeths, but its very very rare. Its just that the game seems to generate female heirs ~50% of the time even with male preference.

**Comment by savagesach** [comment] 2023-04-21 20:30
![image](https://user-images.githubusercontent.com/86676697/233728994-1ce6b399-9521-4480-b33f-5f0dcba7773a.png)
The head of faith title no longer shatters upon female inheritance thanks to equal preference succession. This works as intended.

**Comment by jj248** [comment] 2023-04-21 20:51
Excellent - thank you.  Closing.

**Closed by jj248** 2023-04-21 20:51 UTC
Labels: bug, priority: medium
