### ISSUE TITLE
Elven-Human marriage

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#700] opened 2023-02-20 01:20 UTC
I got a event that my sister could marry the bastard of one of my vassals.

![image](https://user-images.githubusercontent.com/125709421/219988507-a3a7b147-de32-4e93-bd79-5a6c686244e6.png)

**Comment by Remerod** [comment] 2023-02-20 01:31
mentioning this again as i did in an other issue, you leave to much to the imagination, you explain that an event have happened to you. You should explain the event happening to you as of whom you play as and around when, probably the cause of it and why it is a problem, the very bug or problem of the report always need to be clear and not left to guesswork

**Comment by jj248** [comment] 2023-02-20 11:32
I've pushed a fix.  Elves should no longer be valid for this event.  Back to testing.

**Comment by Remerod** [comment] 2023-03-22 22:28
do anyone know what this event is called in code so we can force it in to test it? (but then again if we force it in with console commands then maybe it bypass the block?)

**Closed** 2023-04-11 09:25 UTC
Labels: bug, oddity, priority: low, events
