### ISSUE TITLE
The fall of house Telcontar - Or how to make Aragorn's line survive and rule in case something happens to Eldarion

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#460] opened 2022-08-02 09:23 UTC
AI Aragorn always lets Eldarion be a knight, which often ends up with him being killed in battle or emasculated after capture, before he can even be married (at 40).
As Gondor has Male Only inheritance and Aragorn always marries off his daughters in standard marriages, this ends up creating situations where house Telcontar dies out in a single generation, and where a random Prince inherits the throne of Gondor.

Suggestion : 
- Make Gondor's inheritance Male Preference
- Incite Aragorn to matri-marry at least one of his daughters, by event if need be

**Comment by VectorMaximus** [comment] 2022-08-17 20:39
Added a line of code that should swap it over to male-preference upon Aragorn receiving the title. Now needs testing

**Comment by BriceLeduc** [comment] 2023-02-03 15:09
One problem down. We should also incite Aragorn to matri-marry at least his eldest daughter

**Comment by Vierwood** [comment] 2023-02-03 15:35
We should also reduce the chance of Numenorean blood characters getting wounded or killed in battle, since they live much longer so will naturally have more of a chance of that happening

**Comment by savagesach** [comment] 2023-02-26 22:08
I tested this and gondor's inheritance is still bugged. Even though aragorn has returned, succession is still male only
![image](https://user-images.githubusercontent.com/86676697/221440371-ae22767d-52c9-44e3-860c-09b6b207989d.png)

**Comment by jj248** [comment] 2023-03-08 09:49
Looks to have been fixed now.  Moving back to testing to confirm. 
![image](https://user-images.githubusercontent.com/26043074/223679802-333cfe1d-05c9-4dfd-8166-0e79fbe2a3cf.png)

**Comment by savagesach** [comment] 2023-03-13 16:02
![image](https://user-images.githubusercontent.com/86676697/224758094-d087c218-68e1-46d4-9813-0ab6e22dee1d.png)
this works as intended

**Closed** 2023-03-13 16:07 UTC
Labels: oddity, lore, priority: medium
