### ISSUE TITLE
Trial by Combat CTDs

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#858] opened 2023-04-29 16:32 UTC
![image](https://user-images.githubusercontent.com/76008882/235313444-1dedede3-86bf-423e-bfb9-bb2fd87d197e.png)

Trial by combat CTDs are being reported from the public version. Please try to replicate.

**Comment by JukeJukestar** [comment] 2023-04-30 10:30
We have numerous other reports of the issue and it also happened to the testers.
Unlike before, its not guaranteed to happen anymore.
it can happen both at start and after the duel.

**Comment by BriceLeduc** [comment] 2023-05-01 08:12
It seems like Galadriel is the only character affected anymore

**Comment by JukeJukestar** [comment] 2023-05-01 18:16
Note that it can happen during rival duels too.
@BriceLeduc that is false

**Comment by BriceLeduc** [comment] 2023-05-08 16:22
Pushed a fix, ready for testing

**Comment by savagesach** [comment] 2023-05-08 21:52
I have now tried trial by combats as thranduil, galadriel, saruman, and khamul without any issues. I'll keep testing, but it would be helpful to know how many trial by combats I should run before the issue can be closed

**Comment by savagesach** [comment] 2023-05-08 23:36
https://github.com/jj248/RealmsInExile/issues/622
I'm closing this issue as it's a duplicate of issue 622

**Closed by savagesach** 2023-05-08 23:36 UTC
Labels: bug, priority: critical
